package kz.kasip.designcore

object Lang {


    val kz: Map<String, String> = mapOf(
        ui_designer to "UI Дизайнер",
        status_mode to "Status Mode",
        balance to "Баланс",
        top_up to "Толтыру",
        transaction_history to "Транзакция тарихы",
        withdraw to "Шығару",
        work to "Жұмыс",
        my_works to "Менің жұмыстарым",
        favourites to "Таңдаулылар",
        hidden to "Жасырын",
        viewed to "Қаралғандар",
        teammates to "Командаластар",
        join_kasip_kz to "Kasip.kz ke қосылыңыз",
        join_the_reliable_kasip_kz_platform_and_solve_any_problem_online_with_thousands_of_freelance_services to "Сенімді Kasip.kz платформасына қосылыңыз және мыңдаған фриланс қызметтерімен кез келген мәселені онлайн режимінде шешіңіз",
        email to "Электрондық пошта",
        password to "Құпия сөз",
        repeat_password to "Құпия сөзді қайталаңыз",
        registration to "Тіркелу",
        sign_in to "Кіру",
        welcome_to_kasip_kz to "Kasip.kz сайтына қош келдіңіз",
        please_enter_your_username_or_email_and_password to "Пайдаланушы атыңызды немесе электрондық поштаңызды және құпия сөзіңізді енгізіңіз",
        password to "Құпия сөз",
        enter_all_fields to "Барлық өрістерді енгізіңіз",
        login to "Кіру",
        register_using_your_google_account to "Google есептік жазбаңызбен тіркеліңіз",
        join_kasip_kz to "Kasip.kz ke қосылыңыз",
        join_the_reliable_kasip_kz_platform_and_solve_any_problem_online_with_thousands_of_freelance_services to "Сенімді Kasip.kz платформасына қосылыңыз және мыңдаған фриланс қызметтерімен кез келген мәселені онлайн режимінде шешіңіз",
        registration_with_email to "Электрондық пошта арқылы тіркеу",
        sign_in to "Кіру",
        my_response to "Менің жауабым",
        archive to "Мұрағат",
        rialto to "Биржа",
        general to "Жалпы",
        settings to "Баптаулар",
        profile to "Профиль",
        black_list to "Қара тізім",
        notifications to "Хабарламалар",
        push_notice to "Push-хабарламалар",
        message_sound to "Хабарлама дыбысы",
        log_out to "Шығу",
        search to "Іздеу",
        design to "Дизайн",
        all_your_design_dreams_come_true to "Сіздің барлық дизайн армандарыңыз орындалады",
        logos to "Логотип",
        styles to "Стиль",
        cards to "Визитка",
        social_networks_and_advertising_social_networks_and_advertising to "Әлеуметтік желілер және жарнама Әлеуметтік желілер және жарнама",
        let_new_customers_know_about_your_business to "Жаңа тұтынушыларға сіздің бизнесіңіз туралы хабарлаңыз",
        service_catalog to "Қызметтер каталогы",
        design to "Дизайн",
        it_developing to "IT Разработка",
        texts_and_translates to "Мәтіндер Және Аудармалар",
        social_networks_and_advertising to "Желілер және жарнама",
        business_and_life to "Бизнес Және Өмір",
        audio_video_shooting to "Аудио, Видео, Түсірілім",
        cancel to "Болдырмау",
        viewed_works to "Қаралған жұмыстар",
        view_all to "барлығын көру",
        unique_business_brochure to "Бірегей Бизнес Брошюрасы",
        completing to "Аяқтау:",
        queue to "Кезек:",
        unique_business_brochure to "Бірегей Бизнес Брошюрасы",
        custom_brochures_for_every_project_or_campaign to "Әрбір жоба немесе науқан үшін жеке брошюралар. Толығымен өңделетін Canva үлгілерінен шабыттанып бастаңыз, жоғары сапалы басып шығаруға тапсырыс беріңіз.",
        also_recommend to "Сондай-ақ ұсынамыз",
        unique_design_logo_new_logo to "Бірегей Дизайн логотипі, Жаңа логотип",
        chat to "Сөйлесу",
        order_for_12000tg to "Тапсырыс 12000тг",
        support to "Қолдау",
        message to "Хабарлама",
        support to "Қолдау",
        message to "Хабарлама",
        notification to "Хабарлама",
        new to "Жаңа",
        new_feature_on_kasip_kz_add_your_teemmates_for_the_project_and_do_it_together to "Kasip. kz сайтындағы жаңа Мүмкіндік. жобаға әріптестеріңізді Қосып, оны бірге жасаңыз",
        viewed to "Қаралды",
        see_the_list_of_the_most_interesting_projects_successfully_completed_over_the_past_month_on_kasip_kz to "Өткен айда сәтті аяқталған ең қызықты жобалардың тізімін мына жерден қараңыз Kasip.kz.",
        orders to "Тапсырыстар",
        i_am_a_salesperson to "Мен сатушымын",
        i_am_a_buyer to "Мен сатып алушымын",
        done to "Орындалды",
        all to "Барлығы",
        make_a_business_card_design to "Визитка дизайнын жасаңыз",
        it_company_business_card to "IT-компанияның визит картасы",
        business_card_for_zoo_clinic to "Хайуанаттар бағының клиникасына арналған визитка",
        settings to "Баптаулар",
        email to "Электрондық пошта",
        login to "Логин",
        phone to "Телефон",
        password to "Құпиясөз",
        change_password to "Құпиясөзді өзгерту",
        app_language to "Приложение тілі",
        english to "Kazakh",
        delete_account to "Аккаунтты өшіру",
        change_email to "Электрондық Поштаны Өзгерту",
        email to "Электрондық пошта",
        save_email to "Электрондық Поштаны Сақтау",
        change_login to "Логинді Өзгерту",
        login to "Логин",
        save_login to "Логинді Сақтау",
        change_password to "Құпия Сөзді Өзгерту",
        new_password to "Жаңа Құпиясөз",
        repeat_new_password to "Жаңа Құпия Сөзді Қайталаңыз",
        save_password to "Құпия Сөзді Сақтау",
        profile to "Профиль",
        save to "Сақтау",
        name to "Есім",
        info_about_me to "Мен Туралы Ақпарат",
        speciality to "Мамандығы",
        city to "Қала",
        country to "Мемлекет",
        about_me to "Мен туралы",
        save to "Сақтау",
        enter_information_about_yourself_that_other_users_can_see to "Басқа пайдаланушылар көре алатын өзіңіз туралы ақпаратты енгізіңіз",
        speciality to "Мамандығы",
        save to "Сақтау",
        enter_your_speciality_that_other_users_can_see to "Басқа пайдаланушылар көре алатын мамандығыңызды енгізіңіз",
        my_speciality to "Менің Мамандығым",
        city to "Қала",
        save to "Сақтау",
        write_city_are_you_from to "Қалаңызды жазыңыз",
        country to "Мемлекет",
        save to "Сақтау",
        write_country_are_you_from to "Мемлекетіңізді жазыңыз",
        country to "Мемлекет",
        rialto to "Биржа",
        i_am_a_salesperson to "Мен сатушымын",
        i_am_a_buyer to "Мен сатып алушымын",
        search to "Іздеу",
        translate_17_pages_of_text_from_a_scan to "Сканерлеуден мәтіннің 17 бетін аударыңыз.",
        translate_text_in_english_into_russian_in_a_short_period_of_time to "Қысқа уақыт ішінде ағылшын тіліндегі мәтінді орыс тіліне аударыңыз.",
        history to "Тарихы",
        offer_a_service to "Қызметті ұсыну",
        translate_14_pages_of_text_from_a_scan to "Сканерлеуден мәтіннің 17 бетін аударыңыз.",
        history to "Тарихы",
        offer_a_service to "Қызметті ұсыну",
        filters to "Фильтрлер",
        rubric to "Рубрикалар",
        choose to "Таңдау",
        budget to "Бюджет",
        choose to "Таңдау",
        show_524_results to "524 нәтижені көрсету",
        reset to "Қалпына келтіру",
        rubrics to "Рубрикалар",
        design to "Дизайн",
        logo_and_branding to "Логотип және брендинг",
        web_and_mobile_design to "Веб және мобильді дизайн",
        art_and_illustration to "Өнер және иллюстрация",
        printing to "Басып шығару",
        industrial_design to "Өнеркәсіптік Дизайн",
        outdoor_advertising to "Сыртқы жарнама",
        development_and_it to "Дамыту және IT",
        website_creation to "Веб-сайт құру",
        layout to "Орналасуы",
        mobile_applications to "Мобильді қосымшалар",
        games to "Ойындар",
        servers_and_hosting to "Серверлер және хостинг",
        scripts_and_bots to "Сценарийлер мен боттар",
        audio_and_video_recording to "Аудио және бейне жазу",
        audio_editing to "Аудио өңдеу",
        video_shooting_and_editing to "Бейне түсіру және редакциялау",
        videos to "Бейнелер",
        music_and_songs to "Музыка және әндер",
        intro_and_logo_animation to "Кіріспе және логотип анимациясы",
        audio_recording_and_voice_acting to "Аудиожазба және дауыс шеберлік",
        social_networks_and_advertising to "Әлеуметтік желі және жарнама",
        customer_databases to "Клиенттердің Мәліметтер Базасы",
        advertising_and_pr to "Жарнама және PR",
        social_networks_and_smm to "Әлеуметтік желілер және SMM",
        contextual_advertising to "Контекстік жарнама",
        save to "Сақтау",
        to to "дейін",
        to_5000 to "5000 дейін",
        to_1000 to "10000 дейін",
        save to "Сақтау",
        reset to "Қалпына келтіру",
        offer_a_service to "Қызметті ұсыну",
        translate_17_pages_of_text_from_a_scan to "Сканерлеуден мәтіннің 17 бетін аударыңыз.",
        detail_description_of_project to "Жобаның толық сипаттамасы",
        translate_text_in_english_into_russian_in_a_short_period_of_time_all_count_of_pages_is_17_min_deadline_is_1_day_translate_of_topic_should_have_a_clear_professional_words to "Қысқа уақыт ішінде ағылшын тіліндегі мәтінді орыс тіліне аударыңыз.Барлық беттер саны-17,ең аз мерзімі-1 күн,тақырыптың аудармасында нақты кәсіби сөздер болуы керек.",
        design_industrial_design to "Дизайн: Өнеркәсіптік Дизайн",
        allowable_budget to "Рұқсат етілген бюджет: 9000 тг дейін",
        upload_projects to "Жобаларды жүктеу: 12",
        offers to "Ұсыныстар: 5",
        hired to "Жалданды: 85%",
        active_until_september_15 to "15 қыркүйекке дейін белсенді",
        write_how_you_will_solve_the_client_s_problem to "Клиенттің мәселесін қалай шешетініңізді жазыңыз",
        cost to "Құны",
        deadline to "Мерзімі",
        choose to "Таңдау",
        offer to "Ұсыныс",
        project_name to "Жобаның атауы",
        write_the_name to "Атауын жазу",
        detail_description_of_project to "Жобаның толық сипаттамасы",
        write_the_namedescribe_your_project_requirements_deadlines_and_criteria_in_detail to "Атын жазыңыз, жобаңыздың талаптарын, мерзімдері мен критерийлерін егжей-тегжейлі cипаттаңыз",
        add_the_file to "Файлды қосыңыз",
        rubric to "Рубрика",
        choose_the_rubric to "Рубрика таңдаңыз",
        cost to "Құны",
        add_the_cost to "Құнын қосыңыз",
        post to "Жүктеу",
        rialto to "Биржа",
        create to "Жасау",
        i_am_a_salesperson to "Мен сатушымын",
        i_am_a_buyer to "Мен сатып алушымын",
        you_have_no_active_projects to "Сізде белсенді жобалар жоқ",
        create_a_project_and_find_performers to "Жоба жасаңыз және орындаушыларды табыңыз",
        create_project to "Жоба жасау",
        rialto to "Биржа",
        create to "Жасау",
        i_am_a_salesperson to "Мен сатушымын",
        i_am_a_buyer to "Мен сатып алушымын",
        all to "Барлығы",
        active to "Белсенді",
        created to "құрылды",
        my_works to "Менің Жұмыстарым",
        active to "Белсенді",
        all to "Барлығы",
        booklet_for_mointain_resort to "Тау Курортына арналған буклет",
        booklet_for_furniture_store to "Жиһаз дүкеніне арналған буклет",
        booklet_for_logistic_company to "Логистикалық компанияға буклет",
        viewed_works to "Қаралған Жұмыстар",
        favourite_works to "Таңдаулы Жұмыстар",
        hidden_works to "Жасырын Жұмыстар",
        my_responses to "Менің Жауаптарым",
        send to "Жіберілді",
        translate_17_pages_of_text_from_a_scan to "Сканерлеуден мәтіннің 17 бетін аударыңыз.",
        archive to "Мұрағат",
        presentation_for_seminar to "Семинарға арналған презентация",
        catalog_of_flowers to "Гүлдер каталогы",
        business_journal to "Бизнес Журнал",
        unblock to "Блоктан шығару",
        online to "онлайн",
        message to "Хабарлама",
        do_you_want_to_log_out to "Жүйеден шыққыңыз келе ме?",
        yes to "Иә",
        no to "Жоқ",
        photo_n_video to "Фото Және Видео",
        camera to "Камера",
        cancel to "Болдырмау",
        camera to "Камера",
        file to "Файл",
        cancel to "Болдырмау",
        do_you_want_to_delete_your_account to "Аккаунтыңызды жойғыңыз келе ме?",
        yes to "Иә",
        no to "Жоқ",
        add to "Қосу",
        hide to "Жасыру",
        delete to "Өшіру",
        profile to "Профиль",
        blocking to "Блоктау",
        searhing to "Іздеу",
        delete_chat to "Чатты өшіру",
        do_you_want_to_unblock to "Блоктан шығарғыңыз келе ме?",
        yes to "Иә",
        block_list to "Қара тізім",
        favorite to "Таңдаулы",
        change_name to "Атты өзгерту",
        catalog_rubrics to "Каталог рубрикалары",
        save_name to "Атты сақтау",
        email_is_used to "Email is used",
        message_from_user to "Пайдаланушыдан хабарлама",
        desired_budget to "Қалаған бюджет",
        ok to "OK",
        you_blocked_this_chat to "You blocked this chat",
        you_are_blocked to "You are blocked",
        save_bio to "Мен туралы ақпаратты сақтау",
        save_city to "Қаланы сақтау",
        save_country to "Елді сақтау",
        bio to "Мен Туралы Ақпарат",
        save_speciality to "Мамандықты сақтау",
        password_doesnt_match to "Password doesn't match",
        email_invalid to "Email invalid",
        rate to "Рейтинг",
        save_phone to "Save phone",
        photo to "Photo"
    )
    val eng: Map<String, String> = mapOf(
        favorite to "Favorite",
        ui_designer to "UI Designer",
        status_mode to "Status Mode",
        balance to "Balance",
        top_up to "Top up",
        transaction_history to "Transaction history",
        withdraw to "Withdraw",
        work to "Work",
        my_works to "My works",
        favourites to "Favourites",
        hidden to "Hidden",
        viewed to "Viewed",
        teammates to "Teammates",
        my_response to "My Response",
        archive to "Archive",
        rialto to "Rialto",
        general to "General",
        settings to "Settings",
        profile to "Profile",
        black_list to "Black List",
        notifications to "Notifications",
        push_notice to "Push-Notice",
        message_sound to "Message sound",
        log_out to "Log out",
        search to "Search",
        design to "Design",
        all_your_design_dreams_come_true to "All your design dreams come true",
        logos to "Logos",
        styles to "Styles",
        cards to "Cards",
        social_networks_and_advertising_social_networks_and_advertising to "Social networks and advertising Social networks and advertising",
        let_new_customers_know_about_your_business to "Let new customers know about your business",
        service_catalog to "Service catalog",
        design to "Design",
        it_developing to "IT Developing",
        texts_and_translates to "Texts and Translates",
        social_networks_and_advertising to "Social networks and advertising",
        business_and_life to "Business and Life",
        audio_video_shooting to "Audio,Video,Shooting",
        cancel to "Cancel",
        viewed_works to "Viewed works",
        view_all to "view all",
        unique_business_brochure to "Unique Business Brochure",
        completing to "Completing:",
        queue to "Queue:",
        unique_business_brochure to "Unique Business Brochure",
        chat to "Chat",
        order_for_12000tg to "Order for 12000Tg",
        support to "Support",
        message to "Message",
        join_kasip_kz to "Join Kasip.kz",
        join_the_reliable_kasip_kz_platform_and_solve_any_problem_online_with_thousands_of_freelance_services to "Join the reliable Kasip.kz platform and solve any problem online with thousands of freelance services",
        email to "Email",
        password to "Password",
        repeat_password to "Repeat password",
        registration to "Registration",
        sign_in to "Sign in",
        welcome_to_kasip_kz to "Welcome to Kasip.kz",
        please_enter_your_username_or_email_and_password to "Please enter your username or email and password",
        email to "Email",
        password to "Password",
        enter_all_fields to "Enter all fields",
        login to "Login",
        register_using_your_google_account to "Register using your Google account",
        join_kasip_kz to "Join Kasip.kz",
        join_the_reliable_kasip_kz_platform_and_solve_any_problem_online_with_thousands_of_freelance_services to "Join the reliable Kasip.kz platform and solve any problem online with thousands of freelance services",
        registration_with_email to "Registration with Email",
        sign_in to "Sign in",
        support to "Support",
        message to "Message",
        notification to "Notification",
        new to "New",
        new_feature_on_kasip_kz_add_your_teemmates_for_the_project_and_do_it_together to "New Feature on Kasip.kz.Add your teemmates for the project and do it together",
        viewed to "Viewed",
        see_the_list_of_the_most_interesting_projects_successfully_completed_over_the_past_month_on_kasip_kz to "See the list of the most interesting projects successfully completed over the past month on Kasip.kz.",
        orders to "Orders",
        i_am_a_salesperson to "I am a salesperson",
        i_am_a_buyer to "I am a Buyer",
        done to "Done",
        all to "All",
        make_a_business_card_design to "Make a business card design",
        it_company_business_card to "IT company business card",
        business_card_for_zoo_clinic to "Business card for Zoo Clinic",
        settings to "Settings",
        email to "Email",
        login to "Login",
        phone to "Phone",
        change_password to "Change Password",
        app_language to "App Language",
        english to "English",
        block_list to "Block list",
        delete_account to "Delete Account",
        change_email to "Change Email",
        email to "Email",
        save_email to "Save Email",
        change_login to "Change Login",
        login to "Login",
        save_login to "Save Login",
        change_password to "Change Password",
        password to "Password",
        new_password to "New Password",
        repeat_new_password to "Repeat New Password",
        save_password to "Save Password",
        profile to "Profile",
        save to "Save",
        name to "Name",
        info_about_me to "Info About Me",
        speciality to "Speciality",
        city to "City",
        country to "Country",
        about_me to "About Me",
        save to "Save",
        enter_information_about_yourself_that_other_users_can_see to "Enter information about yourself that other users can see",
        speciality to "Speciality",
        save to "Save",
        enter_your_speciality_that_other_users_can_see to "Enter your speciality that other users can see",
        my_speciality to "My Speciality",
        city to "City",
        save to "Save",
        write_city_are_you_from to "Write city are you from",
        country to "Country",
        save to "Save",
        write_country_are_you_from to "Write country are you from",
        country to "Country",
        rialto to "Rialto",
        i_am_a_salesperson to "I am a salesperson",
        i_am_a_buyer to "I am a Buyer",
        search to "Search",
        translate_17_pages_of_text_from_a_scan to "Translate 17 pages of text from a scan.",
        translate_text_in_english_into_russian_in_a_short_period_of_time to "Translate text in English into Russian in a short period of time.",
        history to "History",
        offer_a_service to "Offer a service",
        translate_14_pages_of_text_from_a_scan to "Translate 14 pages of text from a scan.",
        translate_text_in_english_into_russian_in_a_short_period_of_time to "Translate text in English into Russian in a short period of time.",
        history to "History",
        offer_a_service to "Offer a service",
        filters to "Filters",
        rubric to "Rubric",
        budget to "Budget",
        show_524_results to "Show 524 results",
        reset to "Reset",
        rubrics to "Rubrics",
        design to "Design",
        logo_and_branding to "Logo and branding",
        web_and_mobile_design to "Web and mobile design",
        art_and_illustration to "Art and illustration",
        printing to "Printing",
        industrial_design to "Industrial Design",
        outdoor_advertising to "Outdoor advertising",
        development_and_it to "Development and IT",
        website_creation to "Website creation",
        layout to "Layout",
        mobile_applications to "Mobile applications",
        games to "Games",
        servers_and_hosting to "Servers and hosting",
        scripts_and_bots to "Scripts and bots",
        audio_and_video_recording to "Audio and video recording",
        audio_editing to "Audio editing",
        video_shooting_and_editing to "Video shooting and editing",
        videos to "Videos",
        music_and_songs to "Music and songs",
        intro_and_logo_animation to "Intro and logo animation",
        audio_recording_and_voice_acting to "Audio recording and voice acting",
        social_networks_and_advertising to "Social networks and advertising",
        customer_databases to "Customer Databases",
        advertising_and_pr to "Advertising and PR",
        social_networks_and_smm to "Social networks and SMM",
        contextual_advertising to "Contextual advertising",
        save to "Save",
        budget to "Budget",
        budget to "Бюджет",
        to to "to",
        to_5000 to "to 5000",
        to_1000 to "to 1000",
        save to "Save",
        reset to "Reset",
        offer_a_service to "Offer a service",
        translate_17_pages_of_text_from_a_scan to "Translate 17 pages of text from a scan.",
        detail_description_of_project to "Detail description of project",
        translate_text_in_english_into_russian_in_a_short_period_of_time_all_count_of_pages_is_17_min_deadline_is_1_day_translate_of_topic_should_have_a_clear_professional_words to "Translate text in English into Russian in a short period of time.All count of pages is 17,min deadline is 1 day,translate of topic should have a clear professional words.",
        design_industrial_design to "Design: Industrial Design",
        to_5000tg to "to 5000Tg",
        allowable_budget to "Allowable budget: to 9000Tg",
        upload_projects to "Upload projects: 12",
        offers to "Offers: 5",
        hired to "Hired: 85%",
        write_how_you_will_solve_the_client_s_problem to "Write how you will solve the client’s problem",
        cost to "Cost",
        deadline to "Deadline",
        choose to "Choose",
        offer to "Offer",
        project_name to "Project name",
        write_the_name to "Write the name",
        detail_description_of_project to "Detail description of project",
        write_the_namedescribe_your_project_requirements_deadlines_and_criteria_in_detail to "Write the nameDescribe your project requirements, deadlines and criteria in detail",
        add_the_file to "Add the file",
        rubric to "Rubric",
        choose_the_rubric to "Choose the rubric",
        cost to "Cost",
        add_the_cost to "Add the cost",
        post to "Post",
        rialto to "Rialto",
        create to "Create",
        i_am_a_salesperson to "I am a salesperson",
        i_am_a_buyer to "I am a Buyer",
        you_have_no_active_projects to "You have no active projects",
        create_a_project_and_find_performers to "Create a project and find performers",
        create_project to "Create project",
        rialto to "Rialto",
        create to "Create",
        i_am_a_salesperson to "I am a salesperson",
        i_am_a_buyer to "I am a Buyer",
        all to "All",
        active to "Active",
        created to "created",
        my_works to "My Works",
        active to "Active",
        all to "All",
        booklet_for_mointain_resort to "Booklet for Mointain Resort",
        booklet_for_furniture_store to "Booklet for furniture store",
        booklet_for_logistic_company to "Booklet for Logistic company",
        viewed_works to "Viewed Works",
        favourite_works to "Favourite Works",
        hidden_works to "Hidden Works",
        my_responses to "My Responses",
        send to "Send",
        translate_17_pages_of_text_from_a_scan to "Translate 17 pages of text from a scan",
        archive to "Archive",
        presentation_for_seminar to "Presentation for Seminar",
        catalog_of_flowers to "Catalog of flowers",
        business_journal to "Business Journal",
        unblock to "Unblock",
        online to "online",
        message to "Message",
        do_you_want_to_log_out to "Do you want to Log Out?",
        yes to "Yes",
        no to "No",
        photo_n_video to "Photo & Video",
        camera to "Camera",
        cancel to "Cancel",
        camera to "Camera",
        file to "File",
        cancel to "Cancel",
        do_you_want_to_delete_your_account to "Do you want to delete your account?",
        yes to "Yes",
        no to "No",
        add to "Add",
        hide to "Hide",
        delete to "Delete",
        profile to "Profile",
        blocking to "Blocking",
        searhing to "Searhing",
        delete_chat to "Delete chat",
        do_you_want_to_unblock to "Do you want to Unblock?",
        yes to "Yes",
        no to "No",
        change_name to "Change name",
        catalog_rubrics to "Catalog rubrics",
        save_name to "Save name",
        email_is_used to "Email is used",
        message_from_user to "Message from user",
        desired_budget to "Desired budget",
        ok to "OK",
        you_blocked_this_chat to "You blocked this chat",
        you_are_blocked to "You are blocked",
        save_bio to "Save  Info About Me",
        save_city to "Save City",
        save_country to "Save Country",
        bio to "Info About Me",
        save_speciality to "Save Speciality",
        password_doesnt_match to "Password doesn't match",
        email_invalid to "Email invalid",
        rate to "Rate",
        save_phone to "Save phone",
        photo to "Photo",
    )
    var lang = kz
}